[theme]
primaryColor = "#FF4B4B"
primaryColor = "#5D69B1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
[server]
headless = true
enableCORS = false
font = "sans serif"
